services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: samwilkinson_app
    working_dir: /srv/app
    volumes:
      - ./:/srv/app
      - ./var/data:/srv/app/var/data
    environment:
      - APP_SECRET=change_me_in_production
      - DATABASE_URL=sqlite:///%kernel.project_dir%/var/data/database.sqlite
    networks:
      - samwilkinson

  messenger-consumer:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: samwilkinson_messenger
    working_dir: /srv/app
    command: php bin/console messenger:consume async --time-limit=3600 --memory-limit=128M
    volumes:
      - ./:/srv/app
      - ./var/data:/srv/app/var/data
    environment:
      - APP_SECRET=change_me_in_production
      - DATABASE_URL=sqlite:///%kernel.project_dir%/var/data/database.sqlite
    depends_on:
      - app
    networks:
      - samwilkinson
    restart: unless-stopped

  web:
    image: caddy:2-alpine
    container_name: samwilkinson_web
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - ./:/srv/app
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
    networks:
      - samwilkinson

networks:
  samwilkinson:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
